language: php
php:
- 5.5
- 5.6
- hhvm
- 7
matrix:
  allow_failures:
    - php: 7
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
